apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: py-deploy
  name: service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: py-deploy
  type: NodePort
status:
  loadBalancer: {}
